; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino

; Serial Monitor Settings
monitor_speed = 115200

; Build Flags for ESP32-S3 and Heltec V3
build_flags = 
    -D REGION_US915
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

; Libraries to auto-install
lib_deps =
    jgromes/RadioLib @ ^6.6.0
    olikraus/U8g2 @ ^2.35.19
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
